---
services:

  web:
    git: https://github.com/cloud66-samples/sinatra-postgres-mongo-redis
    git_branch: master
    command: 
    ports: 
      - 9292:80:443
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production

  worker:
    git: https://github.com/cloud66-samples/sinatra-postgres-mongo-redis
    git_branch: master
    command: bundle exec rake resque:work QUEUE=*
    
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production

databases:
  - postgresql
  - redis
  - mongodb
